void reset_to_98(int *n);
void print_array(int*, int);
void swap_int(int*, int*);
int _strlen(char*);
void _puts(char*);
void print_rev(char*);
void rev_string(char*);
void puts2(char*);
void _putchar(char);
char *_strcpy(char *dest, char *src);
void puts_half(char*);
